### ISSUE TITLE
Not outputting results

### ISSUE THREAD

**Issue by glennbarrett** [Cyb3rWard0g/Invoke-ATTACKAPI#2]
I'm not sure if something changed with the API, but the tool does not appear to be outputting results.  Here is what I see when running the basic Invoke-AttackAPI -Category -Technique

Note:  It looks like if you run the GET queries manually in the browser, they do return data there.  Maybe a parsing issue?

![attack_api](https://user-images.githubusercontent.com/1709271/31579989-0dd4bd28-b111-11e7-9152-96c423b6b6d1.PNG)

**Comment by Cyb3rWard0g** [comment]
Hey @glennbarrett  ! You have to first import the module and then you can start using the page selector switches to access the data. The way how the script works is by first pulling pretty much everything from the MITRE ATTACK framework via its API when you import it. So what you have in your image is the script pulling everything back to your computer. Then, that data is filtered by the switches (Tactic, Technique, group, software) and properties such as ID, Description, Name, etc. So do the following:

`import-module invoke-ATTACKAPI.ps1`
![import](https://user-images.githubusercontent.com/9653181/31580101-4fbe6dc6-b114-11e7-80d9-06c36d85a39d.JPG)

`Invoke-ATTACKAPI -Category -Technique | more`
![technique](https://user-images.githubusercontent.com/9653181/31580102-55bfbe3c-b114-11e7-97e6-3512fe6aa393.JPG)

Let me know if this makes sense and if you were able to get it to work. :)

**Comment by glennbarrett** [comment]
Ah, got it.  Yep, that works perfectly.  Thanks!
