### ISSUE TITLE
Unfortunately this does not work anymore

### ISSUE THREAD

**Issue by ghost** [Cyb3rWard0g/Invoke-ATTACKAPI#4]
I think Mitre API has changed. Only returning 404s.

**Comment by olafhartong** [comment]
Correct. This has been extensively communicated by MITRE.

I think Mitre API has changed. Only returning 404s.

**Comment by Cyb3rWard0g** [comment]
Hey @michaelschratt , Correct as @olafhartong said, the API is already deprecated. However, I am now supporting and working the new API via this project https://github.com/Cyb3rWard0g/ATTACK-Python-Client . I hope that helps
